### ISSUE TITLE
Сообщение об неверном вводе появляется ещё до ввода элемента массива или матрицы в .NET Fiddle

### ISSUE THREAD

**Issue by EmilySeville7cfg** [AlvinSeville7cf-NET-projects/ABCNET#41]
**Описание:**
Сообщение об ошибке ввода появляется ещё до ввода элемента массива или матрицы в `.NET Fiddle`.

**Метод воспроизведения:**
Запустить [данный](https://dotnetfiddle.net/RYIl8p) пример.

**Ожидаемое поведение:**
Ввод элемента массива, матрицы или кортежа, и только при неверных данных вывод сообщения об ошибке

**Скриншоты:**
![image](https://user-images.githubusercontent.com/42812113/73069346-8e47cd00-3ebe-11ea-8106-62759e7c2384.png)

**Версия библиотеки:** `версия`

**Comment by Alvin-Seville** [comment]
![image](https://user-images.githubusercontent.com/42812113/73118993-c4438a80-3f6c-11ea-80d1-257264806d25.png)

Написал в поддержку данной `IDE`.
